<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="HVDIVD00MIS1614" name="com.TestCase.Application.BVT.BVTuverseSLflow" tests="1" failures="1" timestamp="25 Jul 2017 16:51:27 GMT" time="81.717" errors="0">
  <testcase name="test" time="81.717" classname="com.TestCase.Application.BVT.BVTuverseSLflow">
    <failure type="java.lang.AssertionError" message="Validate user successfully logged in to MyATT">
      <![CDATA[java.lang.AssertionError: Validate user successfully logged in to MyATT
	at org.testng.Assert.fail(Assert.java:93)
	at com.SupportingFiles.Report.TestPoint(Report.java:442)
	at com.SupportingFiles.LaunchAndLogout.LoginApplication(LaunchAndLogout.java:1144)
	at com.TestCase.Application.BVT.BVTuverseSLflow.test(BVTuverseSLflow.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- com.TestCase.Application.BVT.BVTuverseSLflow -->
